package com.dunglv.calendar.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dunglv.calendar.dao.Rota;
import com.dunglv.calendar.dao.DayTime;
import com.dunglv.calendar.dao.DayOff;

import com.dunglv.calendar.dao.RotaDao;
import com.dunglv.calendar.dao.DayTimeDao;
import com.dunglv.calendar.dao.DayOffDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rotaDaoConfig;
    private final DaoConfig dayTimeDaoConfig;
    private final DaoConfig dayOffDaoConfig;

    private final RotaDao rotaDao;
    private final DayTimeDao dayTimeDao;
    private final DayOffDao dayOffDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rotaDaoConfig = daoConfigMap.get(RotaDao.class).clone();
        rotaDaoConfig.initIdentityScope(type);

        dayTimeDaoConfig = daoConfigMap.get(DayTimeDao.class).clone();
        dayTimeDaoConfig.initIdentityScope(type);

        dayOffDaoConfig = daoConfigMap.get(DayOffDao.class).clone();
        dayOffDaoConfig.initIdentityScope(type);

        rotaDao = new RotaDao(rotaDaoConfig, this);
        dayTimeDao = new DayTimeDao(dayTimeDaoConfig, this);
        dayOffDao = new DayOffDao(dayOffDaoConfig, this);

        registerDao(Rota.class, rotaDao);
        registerDao(DayTime.class, dayTimeDao);
        registerDao(DayOff.class, dayOffDao);
    }
    
    public void clear() {
        rotaDaoConfig.getIdentityScope().clear();
        dayTimeDaoConfig.getIdentityScope().clear();
        dayOffDaoConfig.getIdentityScope().clear();
    }

    public RotaDao getRotaDao() {
        return rotaDao;
    }

    public DayTimeDao getDayTimeDao() {
        return dayTimeDao;
    }

    public DayOffDao getDayOffDao() {
        return dayOffDao;
    }

}
