package com.dunglv.calendar.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dunglv.calendar.dao.Rota;
import com.dunglv.calendar.dao.WeekTime;

import com.dunglv.calendar.dao.RotaDao;
import com.dunglv.calendar.dao.WeekTimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rotaDaoConfig;
    private final DaoConfig weekTimeDaoConfig;

    private final RotaDao rotaDao;
    private final WeekTimeDao weekTimeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rotaDaoConfig = daoConfigMap.get(RotaDao.class).clone();
        rotaDaoConfig.initIdentityScope(type);

        weekTimeDaoConfig = daoConfigMap.get(WeekTimeDao.class).clone();
        weekTimeDaoConfig.initIdentityScope(type);

        rotaDao = new RotaDao(rotaDaoConfig, this);
        weekTimeDao = new WeekTimeDao(weekTimeDaoConfig, this);

        registerDao(Rota.class, rotaDao);
        registerDao(WeekTime.class, weekTimeDao);
    }
    
    public void clear() {
        rotaDaoConfig.getIdentityScope().clear();
        weekTimeDaoConfig.getIdentityScope().clear();
    }

    public RotaDao getRotaDao() {
        return rotaDao;
    }

    public WeekTimeDao getWeekTimeDao() {
        return weekTimeDao;
    }

}
