package com.dunglv.calendar.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dunglv.calendar.dao.Rota;

import com.dunglv.calendar.dao.RotaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rotaDaoConfig;

    private final RotaDao rotaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rotaDaoConfig = daoConfigMap.get(RotaDao.class).clone();
        rotaDaoConfig.initIdentityScope(type);

        rotaDao = new RotaDao(rotaDaoConfig, this);

        registerDao(Rota.class, rotaDao);
    }
    
    public void clear() {
        rotaDaoConfig.getIdentityScope().clear();
    }

    public RotaDao getRotaDao() {
        return rotaDao;
    }

}
