package com.dunglv.calendar.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dunglv.calendar.dao.DayOff;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DAY_OFF.
*/
public class DayOffDao extends AbstractDao<DayOff, Long> {

    public static final String TABLENAME = "DAY_OFF";

    /**
     * Properties of entity DayOff.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DayOfTime = new Property(1, Long.class, "dayOfTime", false, "DAY_OF_TIME");
        public final static Property OffType = new Property(2, Integer.class, "offType", false, "OFF_TYPE");
    };


    public DayOffDao(DaoConfig config) {
        super(config);
    }
    
    public DayOffDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DAY_OFF' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DAY_OF_TIME' INTEGER," + // 1: dayOfTime
                "'OFF_TYPE' INTEGER);"); // 2: offType
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DAY_OFF'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DayOff entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long dayOfTime = entity.getDayOfTime();
        if (dayOfTime != null) {
            stmt.bindLong(2, dayOfTime);
        }
 
        Integer offType = entity.getOffType();
        if (offType != null) {
            stmt.bindLong(3, offType);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DayOff readEntity(Cursor cursor, int offset) {
        DayOff entity = new DayOff( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // dayOfTime
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // offType
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DayOff entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDayOfTime(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOffType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DayOff entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DayOff entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
